
.TH "libstrvar" 1
.SH NAME
String Variable library \- For easy variable management inside application
.SH SYNOPSIS
.SH DESCRIPTION
No description.
.SH AUTHOR
Antti Partanen <aehparta@cc.hut.fi>
.SH BUGS
Report bugs to aehparta@cc.hut.fi or duge @ IRCnet.
.SH "SEE ALSO"
http://west.zeraw.biz/libstrvar/
